<?php declare(strict_types=1);

namespace Symplify\EasyCodingStandard\Tests;

use SplFileInfo;

abstract class AbstractDualRunTestCase extends AbstractFixerTestCase
{
    protected function doTest(string $expected, ?string $input = null, ?SplFileInfo $file = null)
    {
        return parent::doTest($expected, $input, $file); // TODO: Change the autogenerated stub
    }
}
