    //->withSets([
    //      \Symplify\EasyCodingStandard\ValueObject\Set\SetList::SPACES,
    //      \Symplify\EasyCodingStandard\ValueObject\Set\SetList::NAMESPACES,
    //      \Symplify\EasyCodingStandard\ValueObject\Set\SetList::DOCBLOCKS,
    //      \Symplify\EasyCodingStandard\ValueObject\Set\SetList::ARRAYS,
    //      \Symplify\EasyCodingStandard\ValueObject\Set\SetList::COMMENTS,
    //])
